slam_toolbox:
  ros__parameters:
    mode: "mapping"
    debug_logging: false
    throttle_scans: 2  # 实物数据较多，需要节流
    base_frame: "base_link"
    map_frame: "map"
    odom_frame: "odom"
    map_update_interval: 10.0  # 实物更新间隔更长
    max_laser_range: 8.0  # 实物激光范围较小
    minimum_time_interval: 1.0  # 实物需要更长时间间隔
    transform_timeout: 0.5
    tf_buffer_duration: 60.0
    stack_size_to_use: 40000000
    
    # 扫描匹配参数（实物需要更严格）
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 5.0
    link_match_minimum_response_fine: 0.15
    link_scan_maximum_distance: 1.0
    loop_search_maximum_distance: 2.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 2.0
    loop_match_minimum_response_coarse: 0.4
    loop_match_minimum_response_fine: 0.5
    
    # 相关扫描匹配参数
    correlation_search_space_dimension: 0.3
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.05
    
    # 扫描匹配参数续
    loop_search_space_dimension: 4.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.02
    
    # 距离方差参数（实物需要更严格）
    distance_variance_penalty: 0.8
    angle_variance_penalty: 1.5
    
    # 优化参数
    fine_search_angle_offset: 0.001
    coarse_search_angle_offset: 0.2
    coarse_angle_resolution: 0.02
    minimum_angle_penalty: 0.95
    minimum_distance_penalty: 0.8
    use_response_expansion: false
    
    # 实物特定参数
    enable_interactive_mode: false
    position_covariance_scale: 2.0
    orientation_covariance_scale: 2.0